[package]
edition = "2018"
name = "cdc"
publish = false
version = "0.0.1"

[features]
failpoints = ["tikv/failpoints"]
jemalloc = ["tikv/jemalloc"]
mem-profiling = ["tikv/mem-profiling"]
mimalloc = ["tikv/mimalloc"]
portable = ["tikv/portable"]
prost-codec = [
  "engine_rocks/prost-codec",
  "grpcio/prost-codec",
  "kvproto/prost-codec",
  "pd_client/prost-codec",
  "raft/prost-codec",
  "raftstore/prost-codec",
  "tikv/prost-codec",
  "txn_types/prost-codec",
]
protobuf-codec = [
  "engine_rocks/protobuf-codec",
  "grpcio/protobuf-codec",
  "kvproto/protobuf-codec",
  "pd_client/protobuf-codec",
  "raft/protobuf-codec",
  "raftstore/protobuf-codec",
  "tikv/protobuf-codec",
  "txn_types/protobuf-codec",
]
sse = ["tikv/sse"]
tcmalloc = ["tikv/tcmalloc"]

[dependencies]
crossbeam = "0.7.2"
engine_rocks = {path = "../engine_rocks"}
engine_traits = {path = "../engine_traits"}
fail = "0.3"
failure = "0.1"
futures = "0.1"
grpcio = {version = "0.5", default-features = false, features = ["openssl-vendored"]}
hex = "0.4"
keys = {path = "../keys"}
kvproto = {git = "https://github.com/pingcap/kvproto.git", default-features = false}
lazy_static = "1.3"
pd_client = {path = "../pd_client"}
prometheus = {version = "0.8", default-features = false, features = ["nightly", "push"]}
raft = {version = "0.6.0-alpha", default-features = false}
raftstore = {path = "../raftstore"}
resolved_ts = {path = "../resolved_ts"}
security = {path = "../security"}
slog = {version = "2.3", features = ["max_level_trace", "release_max_level_debug"]}
slog-global = {version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1"}
tikv = {path = "../../", default-features = false}
tikv_util = {path = "../tikv_util"}
tokio-threadpool = "0.1"
txn_types = {path = "../txn_types"}

[dev-dependencies]
engine_traits = {path = "../engine_traits"}
panic_hook = {path = "../panic_hook"}
tempfile = "3.0"
test_raftstore = {path = "../test_raftstore"}
test_util = {path = "../test_util"}

[[test]]
name = "tests"
path = "tests/mod.rs"
