[package]
name = "engine_skiplist"
version = "0.0.1"
description = "In-Memory TiKV storage engine built upon crossbeam skiplist"
edition = "2018"
publish = false

[features]
prost-codec = [
  "txn_types/prost-codec",
]
protobuf-codec = [
  "txn_types/protobuf-codec",
]

[dependencies]
engine_traits = { path = "../engine_traits" }
tikv_alloc = { path = "../tikv_alloc" }
tikv_util = { path = "../tikv_util" }
txn_types = { path = "../txn_types" }
hex = "0.3"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
raft = { version = "0.6.0-alpha", default-features = false }
raft-engine = { git = "https://github.com/tikv/raft-engine", default-features = false }
protobuf = "2"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
keys = { path = "../keys" }

[dependencies.crossbeam-skiplist]
git = "https://github.com/crossbeam-rs/crossbeam.git"
tag = "crossbeam-0.7.3"
package = "crossbeam-skiplist"