[package]
name = "resolved_ts"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = ["txn_types/protobuf-codec"]
prost-codec = ["txn_types/prost-codec"]

[dependencies]
crossbeam = "0.7"
engine_traits = { path = "../engine_traits" }
fail = "0.4"
hex = "0.4"
kvproto = { git = "https://github.com/pingcap/kvproto.git", default-features = false }
raft = { version = "0.6.0-alpha", default-features = false }
raftstore = { path = "../raftstore" }
thiserror = "1.0"
tikv = { path = "../../", default-features = false }
tikv_util = { path = "../tikv_util" }
tokio = { version = "0.2", features = ["rt-threaded"]}
txn_types = { path = "../txn_types" }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
